homepages/urls.py
from django.urls import path
from . import views

app_name = 'homepages'

urlpatterns = [
    path('', views.index, name="index"),
    path('single/<int:product_id>', views.single, name="single"),
    path('collections/<str:category_name>', views.collections, name="collections"),
    path('cart', views.cart, name="cart"),
    path('add_cart/<int:product_id>', views.add_cart, name="add_cart"),
    path('remove_all_cart_items', views.remove_all_cart_items, name="remove_all_cart_items"),
    path('remove_cart_item/<str:key>', views.remove_cart_item, name="remove_cart_item"),
    path('update_total/<str:key>', views.update_total, name="update_total"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Luffy'
admin.site.index_title = 'Will become the Priate King'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepages.urls', namespace='homepages')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html', next_page="homepages:index", redirect_authenticated_user=True), name="login"),
    path('logout/', LogoutView.as_view(next_page="homepages:index"), name="logout_view"),
    path('register/', views.register, name="register"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders")
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms

users/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your views here.
@login_required
def checkout(request):
    """Function for checkout"""
    if 'cart_items' in request.session:
        total = 0
        
        for values in request.session['cart_items']:
            # Calculate total price considering discounts
            if request.session['cart_items'][values]['discount_active']:
                # Round down the price to the nearest multiple of 10
                rounded_price = round(round(request.session['cart_items'][values]['price'], -1) 
                             - round(request.session['cart_items'][values]['price'], -1) 
                              * request.session['cart_items'][values]['discount'] / 100, -1) 
                # Calculate the total with the rounded price
                total += int(int(request.session['cart_items'][values]['quantity']) * rounded_price )
            else:
                total += int(request.session['cart_items'][values]['quantity']) * \
                int(request.session['cart_items'][values]['price'])
        print(request.session['cart_items'])       
        return render(request, 'checkout.html', {'cart_items': request.session['cart_items'], 'total': total})
    
    # User entered the url directly
    raise Http404


def register(request):
    """Function for creating a user and authenticating"""
    if request.user.is_authenticated:
        # Redirect user to the homepage if user is already registered
        return HttpResponseRedirect(reverse("homepages:index"))
    
    if request.method == 'POST':
        # User sent the form
        form = UserCreationForm(request.POST)
        
        # User filled the fields correctly 
        if form.is_valid():
            # User is saved in the database
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            # Authericating the user, so the user doesn't have to login after reg.
            auth_user = authenticate(username=username, password=password)
            login(request, auth_user)
            return HttpResponseRedirect(reverse('homepages:index'))
    
    # User just opened the page, send the reg. form structure 
    else: form = UserCreationForm()

    context = {'form': form}
    return render(request, 'register.html', context)


def orders(request):
    """Functions to show the user's orders"""
    return render(request, 'order.html')

users/templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load mathfilters %}

{% block content %}

<section class="py-5 bg-light">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5">
      <div class="col-md-8 order-md-1">
        <h2 class="mb-3">Review Your Order</h2>
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h4 class="text-muted">Your Cart</h4>
          <a href="{% url 'homepages:cart' %}" class="text-decoration-none text-muted">Edit Items</a>
        </div>
        {% for key, value in cart_items.items %}
        <div class="card mb-3 shadow-sm">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="../../{{ value.image|cut:'homepages/' }}" class="img-fluid rounded-start" alt="..." style="max-width: 100px;">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ value.name }}</h5>
                <p class="card-text">Quantity: {{ value.quantity }} | Price: 
                  {% if value.discount_active %}
                     {{ 100|sub:value.discount|mul:value.price|intdiv:1000|mul:10|mul:value.quantity|floatformat:2 }}
                  {% else %}
                     {{ value.price|mul:value.quantity|floatformat:2 }}
                  {% endif %}</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="col-md-4 order-md-0">
        <h2 class="mb-3">Billing & Shipping</h2>
        <form>
          <div class="mb-3">
            <label for="billingName" class="form-label">Full Name</label>
            <input type="text" class="form-control" id="billingName" required>
          </div>
          <div class="mb-3">
            <label for="billingEmail" class="form-label">Email Address</label>
            <input type="email" class="form-control" id="billingEmail" required>
          </div>
          <div class="mb-3">
            <label for="billingState" class="form-label">State</label>
            <select class="form-select" id="billingState" required>
              <option value="">Select Country</option>
              <option value="KZ">Kazakhstan</option>
              </select>
          </div>
          <div class="mb-3">
            <label for="billingCity" class="form-label">City</label>
            <input type="text" class="form-control" id="billingCity" required>
          </div>
          <div class="mb-3">
            <label for="billingAddress" class="form-label">Billing Address</label>
            <input type="text" class="form-control" id="billingAddress" required>
          </div>
          <div class="mb-3">
            <label for="billingZip" class="form-label">Zip Code</label>
            <input type="text" class="form-control" id="billingZip" required>
          </div>
          <div class="d-grid gap-2">
            <button type="submit" class="btn btn-primary">Place Order</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

users/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load mathfilters %}

{% block content %}
    <!-- Login Section -->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
          <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
              <div class="card shadow-sm">
                <div class="card-body">
                  <h2 class="text-center mb-4">Login</h2>
                  <form id="main-content" action="{% url 'users:login' %}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="mb-3">
                      <label for="username" class="form-label">Username</label>
                      <input type="text" class="form-control" id="username" name="username"required>
                      {{ form.email.errors }}
                    </div>
                    <div class="mb-4"> 
                      <label for="password" class="form-label">Password</label>
                      <input type="password" class="form-control" id="password" name="password" required>
                      {{ form.password.errors }}
                    </div>
                    <button type="submit" class="btn btn-outline-dark w-100">Login</button>
                  </form>
                  <div class="mt-3 text-center">
                    <a href="#" style="margin-right: 10px">Forgot Password?</a> 
                    <a href="{% url 'users:register' %}">Create Account</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}

users/templates/orders.html
{% extends "base.html" %}

{% block content %}



{% endblock content %}

users/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load mathfilters %}

{% block content %}
    <!-- Login Section -->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
          <div class="row justify-content-center">
            <div class="col-md-6 col-lg-4">
              <div class="card shadow-sm">
                <div class="card-body">
                  <h2 class="text-center mb-4">Register</h2>
                  <form id="main-content" action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    <div class="mb-3">
                      <label for="username" class="form-label">Username</label>
                      <input type="text" class="form-control" id="username" name="username" required>
                      {{ form.username.errors }}
                    </div>
                    <div class="mb-3"> 
                      <label for="password1" class="form-label">Password</label>
                      <input type="password" class="form-control" name="password1" required>
                      {{ form.password.errors }}
                    </div>
                    <div class="mb-4"> 
                        <label for="password2" class="form-label">Repeat password</label>
                        <input type="password" class="form-control" name="password2" required>
                    </div>
                    <button type="submit" class="btn btn-outline-dark w-100">Register</button>
                  </form>
                  <div class="mt-3 text-center">
                    Already have an account? 
                    <a href="{% url 'users:login' %}">Login</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
{% endblock %}