homepages/urls.py
from django.urls import path
from . import views

app_name = 'homepages'

urlpatterns = [
    path('', views.index, name="index"),
    path('single/<int:product_id>', views.single, name="single"),
    path('collections/<str:category_name>', views.collections, name="collections"),
    path('cart', views.cart, name="cart"),
    path('add_cart/<int:product_id>', views.add_cart, name="add_cart"),
    path('remove_all_cart_items', views.remove_all_cart_items, name="remove_all_cart_items"),
    path('remove_cart_item/<str:key>', views.remove_cart_item, name="remove_cart_item"),
    path('update_total/<str:key>', views.update_total, name="update_total"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'Luffy'
admin.site.index_title = 'Will become the Priate King'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepages.urls', namespace='homepages')),
    path('users/', include('users.urls', namespace='users')),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html', next_page="homepages:index", redirect_authenticated_user=True), name="login"),
    path('logout/', LogoutView.as_view(next_page="homepages:index"), name="logout_view"),
    path('register/', views.register, name="register"),
    path('checkout/', views.checkout, name="checkout"),
    path('orders/', views.orders, name="orders")
]

homepages/models.py
from django.contrib.sessions.backends.db import SessionStore
from django.db import models

class product_category(models.Model):
    """Category description"""
    name = models.CharField(max_length=50, unique=True)

    """Category changes dates"""
    created_at = models.DateTimeField(auto_now_add = True)
    modified_at = models.DateTimeField(auto_now_add = True)
    deleted_at = models.DateTimeField(auto_now_add = True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name_plural = 'Product_categories'


class product(models.Model):
    """Products description"""
    name = models.CharField(max_length = 100)
    desc = models.TextField()
    price = models.IntegerField()
    image = models.ImageField(upload_to='homepages/static/images')

    categories = models.ManyToManyField(product_category)
    
    """Product changes dates"""
    created_at = models.DateTimeField(auto_now_add = True)
    modified_at = models.DateTimeField(auto_now_add = True)
    deleted_at = models.DateTimeField(auto_now_add = True)

    """Product methods"""
    def __str__(self):
        return self.name[:50] + ' ...'


class discount(models.Model):
    """Dicount description"""
    product_name = models.OneToOneField(product, on_delete=models.CASCADE)
    discount_percent = models.DecimalField(max_digits=5, decimal_places=2)
    active = models.BooleanField()

    """Discount changes dates"""
    created_at = models.DateTimeField(auto_now_add = True)
    modified_at = models.DateTimeField(auto_now_add = True)
    deleted_at = models.DateTimeField(auto_now_add = True)

    def __str__(self):
        return str(self.discount_percent) + "%" + "  -  " + self.product_name.name
    

class product_inventory(models.Model):
    """Inventory description"""
    product_name = models.OneToOneField(product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    """Inventory changes dates"""
    created_at = models.DateTimeField(auto_now_add = True)
    modified_at = models.DateTimeField(auto_now_add = True)
    deleted_at = models.DateTimeField(auto_now_add = True)
    
    class Meta:
        verbose_name_plural = 'Product inventories'

    def __str__(self):
        return str(self.quantity) + " - " + self.product_name.name

homepages/forms.py
from django import forms

SIZE_CHOICES = [('xs','XS'),('m','M'), ('xl','XL')]


class Cart(forms.Form):
    """Form with essential information for cart"""
    sizes = forms.ChoiceField(required=True, label="",  label_suffix=" ", widget=forms.RadioSelect(), choices=SIZE_CHOICES) # Radio Select Field
    quantity = forms.IntegerField(label=" ",  label_suffix=" ", widget=forms.NumberInput(), min_value=1, max_value=100)


class UpdateTotal(forms.Form):
    """Form for views.update_total"""
    quantity = forms.IntegerField(label=" ",  label_suffix=" ", widget=forms.NumberInput(), min_value=1, max_value=100)
    

# class EntryForm(forms.ModelForm):
#     class Meta:
#         model = Entry
#         fields = ['text']
#         labels = {'text' : ''}
#         widgets = {'text': forms.Textarea(attrs={'cols':80})}

homepages/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import product, product_category
from .forms import Cart
# from django.contrib.auth import logout

# Create your views here.

def index(request):
    """Shows last 10 modified products"""
    products = product.objects.all().order_by('-modified_at')[:10]

    context = {'products' : products}
    
    return render(request, 'index.html', context)


def single(request, product_id):
    """Renders a single page with a simple form for a specific product"""
    item = product.objects.get(id=product_id)
    form = Cart()
    
    context = {'product':  item, 'form': form}

    return render(request, 'single.html', context)


def collections(request, category_name):
    """Shows items according to the category"""
    items = product_category.objects.get(name=category_name).product_set.all()

    context = {'products': items.order_by('-modified_at'), 'title': category_name}

    return render(request, 'collections.html', context)


def cart(request):
    """Displays the items stored in the cart session"""
    if 'cart_items' in request.session:
        total = 0
        
        for values in request.session['cart_items']:
            # Calculate total price considering discounts
            if request.session['cart_items'][values]['discount_active']:
                if request.session['cart_items'][values]['discount_active']:
                    # Round down the price to the nearest multiple of 10
                    rounded_price = round(round(request.session['cart_items'][values]['price'], -1) 
                                          - round(request.session['cart_items'][values]['price'], -1) 
                                          * request.session['cart_items'][values]['discount'] / 100, -1) 

                    # Calculate the total with the rounded price
                    total += int(int(request.session['cart_items'][values]['quantity']) * rounded_price )
                else:
                    total += int(request.session['cart_items'][values]['quantity']) * \
                        int(request.session['cart_items'][values]['price'])
            else:
                total += int(request.session['cart_items'][values]['quantity']) * \
                         int(request.session['cart_items'][values]['price'])
        return render(request, 'cart.html', {'cart_items': request.session['cart_items'], 'total': total})
    return render(request, 'cart.html', {'cart_items': ''})


def add_cart(request, product_id):
    """Adds items to the cart session"""
    item = get_object_or_404(product, id=product_id)
    if 'quantity' not in request.session:
        request.session['quantity'] = 0

    if request.method != 'GET':
        form = Cart()
    else:
        form = Cart(request.GET)
        if form.is_valid():
            cart_items = request.session.get('cart_items', {})  
            # Get cart_items from session or create an empty dict
            if str(product_id) + request.GET['sizes'] in cart_items:
                # If the same product in the same size is added again, increase its quantity
                cart_items[str(product_id) + request.GET['sizes']]['quantity'] += int(request.GET['quantity'])
                request.session['quantity'] += int(request.GET['quantity'])
            else:
                # Create a new entry in cart_items for the product
                cart_items[str(product_id) + request.GET['sizes']] = {
                    'id': product_id,
                    'name': item.name,
                    'image': str(item.image),
                    'price': item.price,
                    'discount': int(item.discount.discount_percent),
                    'discount_active': item.discount.active,
                    'size': request.GET['sizes'],
                    'quantity': int(request.GET['quantity']),
                    # 'update_total' : UpdateTotal(),
                }
                request.session['quantity'] += int(request.GET['quantity'])
            request.session['cart_items'] = cart_items  # Update cart_items in session
            return HttpResponseRedirect(reverse('homepages:cart'))

    context = {'product': item, 'form': form}
    return render(request, 'single.html', context)


def remove_cart_item(request, key):
    """Removes an item from the cart session"""
    # Check if the key is in the request session
    if 'cart_items' in request.session and key in request.session['cart_items']:
        request.session['quantity'] -= request.session['cart_items'][key]['quantity']
        del request.session['cart_items'][key]
        request.session.modified = True
        return HttpResponseRedirect(reverse('homepages:update_total', args=[key]))
    # Else return cart without any changes
    else:
        # Check if the cart had items or not 
        if 'cart_items' in request.session:
            return HttpResponseRedirect(reverse('homepages:update_total', args=[key]))
        else:
            return render(request, 'cart.html', {'cart_items': ''})


def update_total(request, key):
    """Updates the total price of the cart"""
    try:
        if int(request.GET.get('quantity', 1)) == 0:
            return HttpResponseRedirect(reverse('homepages:remove_cart_item', args=[key]))
    except ValueError:
        return HttpResponseRedirect(reverse('homepages:cart'))
    else:
        if 'cart_items' in request.session and key in request.session['cart_items']:
            # Update quantity and total price
            request.session['quantity'] -= int(request.session['cart_items'][key]['quantity'])
            request.session['cart_items'][key]['quantity'] = abs(int(request.GET['quantity']))
            request.session['quantity'] += abs(int(request.GET['quantity']))
            request.session.modified = True
                
            total = 0
            # Recalculate total price considering discounts
            for values in request.session['cart_items']:
                if request.session['cart_items'][values]['discount_active']:
                    # Round down the price to the nearest multiple of 10
                    rounded_price = round(round(request.session['cart_items'][values]['price'], -1) 
                                          - round(request.session['cart_items'][values]['price'], -1) 
                                          * request.session['cart_items'][values]['discount'] / 100, -1) 

                    # Calculate the total with the rounded price
                    total += int(int(request.session['cart_items'][values]['quantity']) * rounded_price )
                else:
                    total += int(request.session['cart_items'][values]['quantity']) * \
                        int(request.session['cart_items'][values]['price'])

            return render(request, 'cart.html', {'cart_items': request.session['cart_items'], 'total': total})
        
        return HttpResponseRedirect(reverse('homepages:cart'))

def remove_all_cart_items(request):
    """Deleting all cart sessions"""
    del request.session['cart_items']
    del request.session['quantity']
    request.session.modified = True
    return HttpResponseRedirect(reverse('homepages:cart'))

homepages/templates/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
      <meta name="description" content="" />
      <meta name="author" content="" />
      <title>One Piece</title>
      {% load static %}
      {% load bootstrap5 %}
      <!-- Favicon-->
      {% bootstrap_css %}
      {% bootstrap_javascript %}
      <!-- Bootstrap icons-->
      <!-- Core theme CSS (includes Bootstrap)-->
      <link href="{% static 'css/style.css' %}" rel="stylesheet" />
      <link rel="icon" type="image/png" href="{% static 'assets/favicon.png' %}">
   </head>
   <body>
      <!-- Skip to main content button -->
      <div class="skip-link">
         <a href="#main-content">Skip to main content</a>
      </div>
      <!-- Navigation-->
      <nav class="navbar navb navbar-expand-lg navbar-light bg-light">
         <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="{% url 'homepages:index' %}">One Piece</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                  <li class="nav-item"><a class="nav-link" aria-current="page" href="{% url 'homepages:index' %}">Home</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'homepages:collections' 'Men' %}">Men</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'homepages:collections' 'Women' %}">Women</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'homepages:collections' 'All items' %}">All Products</a></li>
                  <li class="nav-item dropdown">
                     <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Shop</a>
                     <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'homepages:collections' 'All items' %}">All Products</a></li>
                        <li>
                           <hr class="dropdown-divider" />
                        </li>
                        <li><a class="dropdown-item" href="{% url 'homepages:collections' 'Anime' %}">Popular Items</a></li>
                        <li><a class="dropdown-item" href="{% url 'homepages:collections' 'All items' %}">New Arrivals</a></li>
                     </ul>
                  </li>
               </ul>
               <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:logout_view' %}">Logout</a>
                     </li>
                    {% else %}
                     <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:login' %}">Login</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link active" href="{% url 'users:register' %}">Register</a>
                     </li>
                    {% endif %}
               </ul>
               <form class="d-flex" action="{% url 'homepages:cart' %}" method="get">
                  {% csrf_token %}
                  <button class="btn btn-outline-dark" type="submit">
                  <i class="bi-cart-fill me-1"></i>
                  Cart
                  <span class="badge bg-dark text-white ms-1 rounded-pill">
                  {% if request.session.quantity %}
                  {{ request.session.quantity }}
                  {% else %}
                  0
                  {% endif %}
                  </span>
                  </button>
               </form>
            </div>
         </div>
      </nav>
      {% block content %}{% endblock content %}
      <footer class="py-5 bg-dark">
         <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; One Piece {% now "Y" %}</p>
         </div>
      </footer>
   </body>
</html>

homepages/templates/cart.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}

<section class="py-5 bg-light">
   <div class="container px-4 px-lg-5 mt-5">
      <div class="table-responsive" id ="main-content">
         <table class="table table-striped table-hover">
            {% if cart_items %}
            <thead>
               <tr>
                  <th scope="col" style="width: 400px;">Product</th>
                  <th scope="col" class="text-right">Price</th>
                  <th scope="col">Quantity</th>
                  <th scope="col" class="text-right">Total</th>
                  <th scope="col">Actions</th>
               </tr>
            </thead>
            <tbody>
               {% for key, value in cart_items.items %}
               <tr>
                  <td>
                     <div class="d-flex align-items-center">
                        <img src="../{{ value.image|cut:'homepages/' }}" alt="{{ value.name }}" style="height: 100px; object-fit: cover; margin-right: 10px;">
                        <div class="text-left">
                           <p class="mb-1">{{ value.name }}</p>
                           <p class="text-muted mb-0">Size: {{ value.size|upper }}</p>
                        </div>
                     </div>
                  </td>
                  <td class="text-right">
                     {% if value.discount_active %}
                        {{ 100|sub:value.discount|mul:value.price|intdiv:1000|mul:10|floatformat:2 }}
                     {% else %}
                        {{ value.price|floatformat:2 }}
                     {% endif %}
                     &#8376;
                  </td>
                  <td>
                     <form method="get" action="{% url 'homepages:update_total' key %}">
                        {% csrf_token %}
                        <input type="number" name="quantity" value="{{ value.quantity }}" min="1" max="100" class="form-control form-control-sm" style="width: 80px">
                  </td>
                  <td class="text-right">
                  {% if value.discount_active %}
                     {{ 100|sub:value.discount|mul:value.price|intdiv:1000|mul:10|mul:value.quantity|floatformat:2 }}
                  {% else %}
                     {{ value.price|mul:value.quantity|floatformat:2 }}
                  {% endif %}
                  &#8376;
                  </td>
                  <td>
                  <input type="submit" class="btn btn-sm btn-primary" value="Update total" />
                  <a href="{% url 'homepages:remove_cart_item' key %}" class="btn btn-sm btn-danger">Remove</a>
                  </td>
               </tr>
               </form>
               {% endfor %}
            </tbody>
            <tfoot>
               <tr>
                  <th colspan="2"></th>
                  <th class="text-right">Total:</th>
                  <th class="text-right">{{total|floatformat:2}} &#8376;</th>
                  <th class="text-right">
                     <a href="{% url 'users:checkout' %}" class="btn btn-sm btn-primary">Checkout</a>
                     <a href="{% url 'homepages:remove_all_cart_items' %}" class="btn btn-sm btn-danger">Remove all</a>
                  </th>
               </tr>
            </tfoot>
            {% else %}
            <thead>
               <tr>
                  <td colspan="5" class="text-center py-5">
                     <h1>Your cart is empty</h1>
                  </td>
               </tr>
            </thead>
            {% endif %}
         </table>
      </div>
   </div>
</section>
{% endblock content %}

homepages/templates/collections.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load mathfilters %}
{% block content %}
<!-- Header-->
<header class="py-5" style="background-color: #090b0b;">
   <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
         <h1 class="display-4 fw-bolder" style="color: #e6ca3d;">{{ title }}</h1>
         <p class="lead fw-normal mb-0" style="color: #e6ca3d;">Shop in Style With Mugiwara Pirate Ship Nakamas</p>
      </div>
   </div>
</header>
<!-- Section-->
<section class="py-5" id ="main-content" style="height: 80vh">
   <div class="container px-4 px-lg-5 mt-5">
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
         {% for product in products %}
         {% if product.discount.active %}
         <div class="col mb-5">
            <div class="card h-100">
               <!-- Sale badge-->
               <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
               <!-- Product image-->
               <img class="card-img-top" src="../{{ product.image|cut:"homepages/" }}" alt="..." style="max-height: 250px; object-fit: contain; margin: auto;">
               <!-- Product details-->
               <div class="card-body p-4">
                  <div class="text-center">
                     <!-- Product name-->
                     <h5 class="fw-bolder">{{ product.name }}</h5>
                     <!-- Product reviews-->
                     <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                     </div>
                     {{ 100|sub:product.discount.discount_percent|mul:product.price|intdiv:1000|mul:10 }} &#8376
                     <span class="text-muted text-decoration-line-through">{{ product.price }} &#8376 </span>
                  </div>
               </div>
               <!-- Product actions-->
               <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                  <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'homepages:single' product.id %}">Add to cart</a></div>
               </div>
            </div>
         </div>
         {% else %}
         <div class="col mb-5">
            <div class="card h-100">
               <!-- Product image-->
               <div class="d-flex justify-content-center align-items-center" style="height: 250px;">
                  <img class="card-img-top" src="../{{ product.image|cut:"homepages/" }}" alt="..." style="max-height: 100%; max-width: 100%; object-fit: contain;">
               </div>
               <!-- Product details-->
               <div class="card-body p-4">
                  <div class="text-center">
                     <!-- Product name-->
                     <h5 class="fw-bolder">{{ product.name }}</h5>
                     <!-- Product price-->
                     {{ product.price }} &#8376 
                  </div>
               </div>
               <!-- Product actions-->
               <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                  <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'homepages:single' product.id %}">Add to cart</a></div>
               </div>
            </div>
         </div>
         {% endif %}
         {% endfor %}
      </div>
   </div>
</section>
{% endblock content %}

homepages/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load mathfilters %}
{% block content %}
<!-- Header-->
<header class="py-5" style="background-color: #090b0b;">
   <div class="container px-4 px-lg-5 my-5">
      <div class="text-center text-white">
         <h1 class="display-4 fw-bolder" style="color: #e6ca3d;">Shop in style</h1>
         <p class="lead fw-normal mb-0" style="color: #e6ca3d;">With Mugiwara Pirate Ship Nakamas</p>
      </div>
   </div>
</header>
<!-- Section-->
<section class="py-5" id="main-content">
   <div class="container px-4 px-lg-5 mt-5">
      <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
         {% for product in products %}
         {% if product.discount.active %}
         <div class="col mb-5">
            <div class="card h-100">
               <!-- Sale badge-->
               {% if product.discount.active %}
               <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Sale</div>
               {% endif %}
               <!-- Product image-->
               <img class="card-img-top" src="{{ product.image|cut:"homepages/" }}" alt="..." style="max-height: 250px; object-fit: contain; margin: auto;">
               <!-- Product details-->
               <div class="card-body p-4">
                  <div class="text-center">
                     <!-- Product name-->
                     <h5 class="fw-bolder">{{ product.name }}</h5>
                     <!-- Product reviews-->
                     <div class="d-flex justify-content-center small text-warning mb-2">
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                        <div class="bi-star-fill"></div>
                     </div>
                     {% if product.discount.active %}
                     {{ 100|sub:product.discount.discount_percent|mul:product.price|intdiv:1000|mul:10 }} &#8376
                     <span class="text-muted text-decoration-line-through">{{ product.price }} &#8376 </span>
                     {% else %}
                     {{ product.price }} &#8376
                     {% endif %}
                  </div>
               </div>
               <!-- Product actions-->
               <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                  <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'homepages:single' product.id %}">Add to cart</a></div>
               </div>
            </div>
         </div>
         {% else %}
         <div class="col mb-5">
            <div class="card h-100">
               <!-- Product image-->
               <div class="d-flex justify-content-center align-items-center" style="height: 250px;">
                  <img class="card-img-top" src="{{ product.image|cut:"homepages/" }}" alt="..." style="max-height: 100%; max-width: 100%; object-fit: contain;">
               </div>
               <!-- Product details-->
               <div class="card-body p-4">
                  <div class="text-center">
                     <!-- Product name-->
                     <h5 class="fw-bolder">{{ product.name }}</h5>
                     <!-- Product price-->
                     {{ product.price }} &#8376 
                  </div>
               </div>
               <!-- Product actions-->
               <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                  <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'homepages:single' product.id %}">Add to cart</a></div>
               </div>
            </div>
         </div>
         {% endif %}
         {% endfor %}
      </div>
   </div>
</section>
{% endblock content %}

homepages/templates/single.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap5 %}
{% load mathfilters %}
{% block content %}
<!-- Product details -->
<section class="py-5" id ="main-content">
   <div class="container px-4 px-lg-5 mt-5">
      <div class="row gx-4 gx-lg-5 justify-content-center align-items-center">
         <div class="col-lg-6 text-center text-lg-start">
            <img style="max-height:35em;"class="img-fluid" src="../{{ product.image|cut:"homepages/" }}" alt="{{ product.name }}">
         </div>
         <div class="col-lg-6">
            <div class="text">
               <h1 class="fw-bolder">{{ product.name }}</h1>
               <div class="d-flex justify-content-center justify-content-lg-start small text-warning mb-2"></div>
               {% if product.discount.active %}
               <h2>{{ 100|sub:product.discount.discount_percent|mul:product.price|intdiv:1000|mul:10 }} &#8376; 
                  <span class="text-muted text-decoration-line-through">{{ product.price }} &#8376;</span>
               </h2>
               {% else %}
               <h2>{{ product.price }} &#8376;</h2>
               {% endif %}
               <p class="lead"> {{ product.desc }}</p>
               <form action="{% url 'homepages:add_cart' product.id %}" method="get" class="row g-2 align-items-center">
                  {% csrf_token %}
                  {{ form.errors.sizes }}
                  {{ form.errors.quantity }}
                  {% for field in form %}
                  <div class="col-auto">
                     {% if field.field.choices %}
                     <div class="btn-group" role="group">
                        {% for choice in field.field.choices %}
                        <input type="radio" id="{{choice.0}}" name="sizes" value="{{choice.0}}" class="btn-check" autocomplete="off" required>
                        <label class="btn btn-outline-dark" for="{{choice.0}}">{{choice.1}}</label>
                        {% endfor %}
                     </div>
                  </div>
                  {% else %}
                  <input type="number" name="quantity" class="form-control" value="1" min="1" max="100"style="width: 80px;">
            </div>
            {% endif %}
            {% endfor %}
            <!-- Add more size buttons as needed -->
            <div class="col-auto">
            <button type="submit" class="btn btn-outline-dark">Add to cart</button>
            </div>
            </form>
         </div>
      </div>
   </div>
   </div>
</section>
{% endblock content %}